# Generated by Django 3.1.12 on 2022-04-13 23:04
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
               
            ],
        ),
        migrations.CreateModel(
            name='Graphs',
            fields=[
               
            ],
        ),
    ]
